In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.loadtxt('x.txt')

In [3]:
y = np.loadtxt('y.txt')

In [4]:
np.random.permutation(10)

array([5, 6, 3, 7, 1, 0, 8, 4, 2, 9])

In [5]:
np.random.seed(1)
shuffle = np.random.permutation(len(y))

In [6]:
test_size = 0.25
size = int(len(X) * test_size)
size

37

In [7]:
test_index = shuffle[:size]
train_index = shuffle[size:]

In [8]:
test_index

array([ 14,  98,  75,  16, 131,  56, 141,  44,  29, 120,  94,   5, 102,
        51,  78,  42,  92,  66,  31,  35,  90,  84,  77,  40, 125,  99,
        33,  19,  73, 146,  91, 135,  69, 128, 114,  48,  53])

In [9]:
train_index

array([ 28,  54, 108, 112,  17, 119, 103,  58, 118,  18,   4,  45,  59,
        39,  36, 117, 139, 107, 132, 126,  85, 122,  95,  11, 113, 123,
        12,   2, 104,   6, 127, 110,  65,  55, 144, 138,  46,  62,  74,
       116,  93, 100,  89,  10,  34,  32, 124,  38,  83, 111, 149,  27,
        23,  67,   9, 130,  97, 105, 145,  87, 148, 109,  64,  15,  82,
        41,  80,  52,  26,  76,  43,  24, 136, 121, 143,  49,  21,  70,
         3, 142,  30, 147, 106,  47, 115,  13,  88,   8,  81,  60,   0,
         1,  57,  22,  61,  63,   7,  86,  96,  68,  50, 101,  20,  25,
       134,  71, 129,  79, 133, 137,  72, 140,  37])

In [10]:
y[test_index]

array([0., 1., 1., 0., 2., 1., 2., 0., 0., 2., 1., 0., 2., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 0., 2., 1., 0., 0., 1., 2., 1., 2., 1., 2.,
       2., 0., 1.])

In [11]:
X_test = X[test_index]
y_test = y[test_index]
X_train = X[train_index]
y_train = y[train_index]

In [12]:
from ML.knn import kNN_classify

In [13]:
y_predict = kNN_classify(X_train, y_train, X_test)

In [14]:
np.array(y_predict) == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
sum(np.array(y_predict) == y_test)

37

In [16]:
len(X_test)

37

In [17]:
sum(np.array(y_predict) == y_test) / len(X_test)

1.0

In [19]:
from ML.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, seed = 1)

In [21]:
y_predict = kNN_classify(X_train, y_train, X_test)

In [22]:
sum(np.array(y_predict) == y_test) / len(X_test)

1.0